# Generated by Django 4.2.7 on 2023-11-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "task", "verbose_name_plural": "tasks"},
        ),
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
        migrations.AddField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="tasks.tag"),
        ),
    ]
